VALORANT_RANKS = ["Unranked", "Iron 1", "Iron 2", "Iron 3", "Bronze 1", "Bronze 2", "Bronze 3", "Silver 1", "Silver 2",
                  "Silver 3", "Gold 1", "Gold 2", "Gold 3", "Platinum 1", "Platinum 2", "Platinum 3", "Diamond 1",
                  "Diamond 2", "Diamond 3", "Immortal 1", "Immortal 2", "Immortal 3", "Radiant"]

RANKS_URL = {"Unranked": "https://www.metasrc.com/assets/images/valorant/ranks/unranked.png",
             "Iron 1": "https://img.rankedboost.com/wp-content/uploads/2020/04/Iron-1-Valorant-Rank.png",
             "Iron 2": "https://img.rankedboost.com/wp-content/uploads/2020/04/Iron-2-Valorant-Rank.png",
             "Iron 3": "https://img.rankedboost.com/wp-content/uploads/2020/04/Iron-3-Valorant-Rank.png",
             "Bronze 1": "https://img.rankedboost.com/wp-content/uploads/2020/04/Bronze-1-Valorant-Rank.png",
             "Bronze 2": "https://img.rankedboost.com/wp-content/uploads/2020/04/Bronze-2-Valorant-Rank.png",
             "Bronze 3": "https://img.rankedboost.com/wp-content/uploads/2020/04/Bronze-3-Valorant-Rank.png",
             "Silver 1": "https://img.rankedboost.com/wp-content/uploads/2020/04/Silver-1-Valorant-Rank.png",
             "Silver 2": "https://img.rankedboost.com/wp-content/uploads/2020/04/Silver-2-Valorant-Rank.png",
             "Silver 3": "https://img.rankedboost.com/wp-content/uploads/2020/04/Silver-3-Valorant-Rank.png",
             "Gold 1": "https://img.rankedboost.com/wp-content/uploads/2020/04/Gold-1-Valorant-Rank.png",
             "Gold 2": "https://img.rankedboost.com/wp-content/uploads/2020/04/Gold-2-Valorant-Rank.png",
             "Gold 3": "https://img.rankedboost.com/wp-content/uploads/2020/04/Gold-3-Valorant-Rank.png",
             "Platinum 1": "https://img.rankedboost.com/wp-content/uploads/2020/04/Platinum-1-Valorant-Rank.png",
             "Platinum 2": "https://img.rankedboost.com/wp-content/uploads/2020/04/Platinum-2-Valorant-Rank.png",
             "Platinum 3": "https://img.rankedboost.com/wp-content/uploads/2020/04/Platinum-3-Valorant-Rank.png",
             "Diamond 1": "https://img.rankedboost.com/wp-content/uploads/2020/04/Diamond-1-Valorant-Rank.png",
             "Diamond 2": "https://img.rankedboost.com/wp-content/uploads/2020/04/Diamond-2-Valorant-Rank.png",
             "Diamond 3": "https://img.rankedboost.com/wp-content/uploads/2020/04/Diamond-3-Valorant-Rank.png",
             "Immortal 1": "https://img.rankedboost.com/wp-content/uploads/2020/04/Immortal-1-Valorant-Rank.png",
             "Immortal 2": "https://img.rankedboost.com/wp-content/uploads/2020/04/Immortal-2-Valorant-Rank.png",
             "Immortal 3": "https://img.rankedboost.com/wp-content/uploads/2020/04/Immortal-3-Valorant-Rank.png",
             "Radiant": "https://img.rankedboost.com/wp-content/uploads/2020/04/Valorant-Rank-1.png"}
